---
title: "Milestone2 - Chad Crowe"
author: "Chad Crowe"
date: "11/30/2019"
output: html_document
---

```{r echo=FALSE, include=FALSE, warning=FALSE}
#The clean dataset in the folder has been updated to not include imputation. We should each be running at least 4 models:

#-1 undersampled with transactions
#-1 undersampled with products
#-1 no sampling with transactions
#-1 no sampling with products

#If we all are clear and what we are doing, then I am cool meeting Sunday after thanksgiving to compare results and split up the report writing. If not, we can meet this Sunday.
library(ISLR)
library(GGally)
library(tidyverse)
library(caret)
library(e1071)
library(pROC)
```

```{r echo=FALSE}
dataset <- read.csv("/Users/ccrowe/github/Milestone2/CleanDataset.csv")
```

```{r preprocess, echo=FALSE, warning=FALSE}

dataset <- dataset %>% mutate_if(is.character, as.factor)
data_num <- dataset %>% select_if(is.numeric)
data_non_num <- dataset %>% select_if(~!is.numeric(.x))

pre_proc_impute_median <- preProcess(data_num, method = "medianImpute") # this will take longer
data_imputed_median <- cbind(data_non_num, predict(pre_proc_impute_median, data_num))
#summary(data_imputed_median)

dataset <- data_imputed_median
dataset= subset(dataset, select = -c(total_products))

#dataset <- head(dataset, 5000) # REMOVE LATER ON
```

```{r model_params, warning=FALSE}
target_var <- 'churned'
positive_class <- 'Yes'
negative_class <- 'No'
threshold <- 0.5
model_type <- "knn"
model_form <- churned ~ .
```

```{r split, warning=FALSE}
trainIndex <- createDataPartition(dataset[[target_var]], p = 0.7, list = FALSE)
data_train <- dataset[trainIndex,]
data_test <- dataset[-trainIndex,]
```

```{r knn, warning=FALSE}
set.seed(1)

tuneGrid <- expand.grid(k = 3:7) 
trControl <- trainControl(method = 'cv', number = 5, savePredictions = TRUE, classProbs = TRUE, summaryFunction = twoClassSummary)
knn_fit <- train(as.formula(model_form), data = data_train, method = model_type, tuneGrid = tuneGrid, preProc = c("center", "scale"))

# let's predict its performance on the validation / test data
knn_pred <- knn_fit %>% predict(newdata = data_test, type = 'raw')
confusionMatrix(knn_pred, data_test[[target_var]], positive = positive_class)

# ROC curve
knn_probs <- knn_fit %>% predict(newdata = data_test, type = 'prob')
roc(data_test[[target_var]], knn_probs[, positive_class], plot = TRUE, print.auc = TRUE, legacy.axes = TRUE, levels = c(negative_class, positive_class))

#data_test <- read.csv("/Users/ccrowe/github/Milestone2/TestDataset.csv")

```


