---
title: "Milestone2 - Chad Crowe"
author: "Chad Crowe"
date: "11/30/2019"
output: html_document
---

```{r echo=FALSE, include=FALSE, warning=FALSE}
#The clean dataset in the folder has been updated to not include imputation. We should each be running at least 4 models:

#-1 undersampled with transactions
#-1 undersampled with products
#-1 no sampling with transactions
#-1 no sampling with products

#If we all are clear and what we are doing, then I am cool meeting Sunday after thanksgiving to compare results and split up the report writing. If not, we can meet this Sunday.
library(ISLR)
library(GGally)
library(tidyverse)
library(caret)
library(e1071)
library(pROC)
```

```{r model_params, warning=FALSE}
target_var <- 'churned'
positive_class <- 'Yes'
negative_class <- 'No'
model_type <- "knn"
model_form <- churned ~ .
```

```{r echo=FALSE}
data_train <- read.csv("/Users/ccrowe/github/Milestone2/CleanDataset_train.csv")
data_test <- read.csv("/Users/ccrowe/github/Milestone2/CleanDataset_test.csv")

dataset<-merge(data_train,data_test,all=TRUE)
```

```{r preprocess, echo=FALSE, warning=FALSE}

dataset <- dataset %>% mutate_if(is.character, as.factor)
data_num <- dataset %>% select_if(is.numeric)
data_non_num <- dataset %>% select_if(~!is.numeric(.x))

pre_proc_impute_median <- preProcess(data_num, method = "medianImpute") # this will take longer
data_imputed_median <- cbind(data_non_num, predict(pre_proc_impute_median, data_num))

dataset <- data_imputed_median

# Add Column
#dataset$ratio = dataset$total_transactions/dataset$total_products
# Remove Columns
dataset= subset(dataset, select = -c(total_transactions))
#dataset= subset(dataset, select = -c(total_products))
```


```{r split, warning=FALSE}
#dataset <- read.csv("/Users/ccrowe/github/Milestone2/CleanDataset.csv")
#dataset <- head(dataset, 2000) # REMOVE LATER ON

dataset <- head(dataset, nrow(dataset)) # REMOVE LATER ON
#data_train <- head(data_train, 75)
#data_test <- head(data_test, 25)

trainIndex <- createDataPartition(dataset[[target_var]], p = 0.7, list = FALSE)
data_train <- dataset[trainIndex,]
data_test <- dataset[-trainIndex,]

```



```{r knn, warning=FALSE}
library(RANN)
library(ISLR)
library(caret)
trControl <- trainControl(method = 'cv', number = 5, savePredictions = TRUE, classProbs = TRUE, summaryFunction = twoClassSummary)#, sampling = 'down')
tuneGrid <- expand.grid(k = 1:5)
knn_fit <- train(as.formula(model_form), data = data_train, method = model_type, tuneGrid = tuneGrid,trControl = trControl, preProc = c("center", "scale"), metric = 'ROC')

# let's predict its performance on the validation / test data
knn_pred <- knn_fit %>% predict(newdata = data_test, type = 'raw')
confusionMatrix(knn_pred, data_test[[target_var]], positive = positive_class)

# ROC curve
knn_probs <- knn_fit %>% predict(newdata = data_test, type = 'prob')
roc(data_test[[target_var]], knn_probs[, positive_class], plot = TRUE, print.auc = TRUE, legacy.axes = TRUE, levels = c(negative_class, positive_class))

#data_test <- read.csv("/Users/ccrowe/github/Milestone2/TestDataset.csv")
summary(knn_fit)
print("No Sampling No Transactions KNN")
```

```{r test_predictions}
#test <- read.csv("/Users/ccrowe/github/Milestone2/FinalTestData.csv")
#test_predictions <- knn_fit %>% predict(newdata = test, type = 'prob')

```

 [1] "X"                                "total_products"                  
 [3] "total_transactions"               "total_revenue"                   
 [5] "total_usage"                      "total_accounts"                  
 [7] "churned"                          "Business_Code"                   
 [9] "Location_Type"                    "Year_Started"                    
[11] "Public_Private_Indicator"         "Owns_Rents_Code"                 
[13] "Square_Footage"                   "Subsidiary_Indicator"            
[15] "Manufacturing_Indicator"          "Legal_Status_Code"               
[17] "Currency_Code"                    "Status_Code"                     
[19] "Population_Code"                  "Hierarchy_Code"                  
[21] "Revenue__US_Dollars_"             "Number_of_Family_Members"        
[23] "Employees_Here"                   "Employee_Count_Total"            
[25] "Domestic_Ultimate_Employee_Count" "Domestic_Ultimate_Revenue"       
[27] "Global_Ultimate_Indicator"        "Major_Industry_Category_Name"    
[29] "YearCreated"                      "PropMissing"  
